# Build only merge request and default branch.
# save time for quick demo pushes
include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

# Build with moveit
foxy-moveit2:
  image:
    name: registry.gitlab.com/rosi-ap/rosiap_docker_images:moveit-foxy-nightly

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .ccache/

  before_script:
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master

  variables:
    ISOLATION: "shell"
    ROS_DISTRO: "foxy"
    CCACHE_DIR: "${CI_PROJECT_DIR}/.ccache"

  script:
    - .industrial_ci/gitlab.sh
  
  # after_script:
  #   - bash <(curl -s https://codecov.io/bash)

# Build Documentation
sphinx-docs:
  image: ubuntu:latest

  before_script:
    - apt-get -qq update

    # Install Python3 dependencies
    - apt-get install -y -qq python3-pip python3-dev
    - python3 -m pip install --upgrade setuptools

    # Install Sphinx Latex PDF dependencies
    - DEBIAN_FRONTEND="noninteractive" apt-get install -y -qq texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk

    # Install Sphinx
    - python3 -m pip install --upgrade sphinx sphinx-rtd-theme recommonmark

    # Install Lint tools
    - DEBIAN_FRONTEND="noninteractive" apt-get install -y -qq enchant git
    - python3 -m pip install --upgrade doc8 pyenchant sphinxcontrib-spelling

  script:
    # Make html and pdf
    - make -C docs/sphinx html
    - make -C docs/sphinx latexpdf
    # Run Doc8 Lint
    # - doc8 docs/sphinx --ignore-path docs/sphinx/build --max-line-length 999
    # Check Spelling
    # - make -C docs/sphinx spelling
    # - find . -name *.spelling -exec cat {} \;
    # - sh -c "! find . -name *.spelling | grep -q ."

  artifacts:
    paths:
      - docs/sphinx/build/html/
      - docs/sphinx/build/latex/emd.pdf
    expire_in: 1 day

# Build API Documentation
doxygen-docs:
  image: ubuntu:latest

  before_script:
    - apt-get -qq update
    - apt-get -y -qq install doxygen

  script:
    - (cd docs/doxygen && doxygen grasp_planner)
  
  artifacts:
    paths:
      - docs/doxygen/html/
    expire_in: 1 day
