dynamic_safety_demo_node:
  ros__parameters:
    planning_scene_monitor_options:
      name: "planning_scene_monitor"
      robot_description: "robot_description"
      joint_state_topic: "/joint_states"
      attached_collision_object_topic: "/moveit_cpp/planning_scene_monitor"
      publish_planning_scene_topic: "/moveit_cpp/publish_planning_scene"
      monitored_planning_scene_topic: "/moveit_cpp/monitored_planning_scene"
      wait_for_initial_state_timeout: 10.0
    
    planning_pipelines:
      #namespace: "moveit_cpp"  # optional, default is ~
      pipeline_names: ["ompl"]
    
    plan_request_params:
      planning_attempts: 1
      planning_time: 0.5
      planning_pipeline: ompl
      max_velocity_scaling_factor: 1.0
      max_acceleration_scaling_factor: 1.0

    # Load octomap
    load_octomap: true

    # Dynamic safety parameters
    rate: 20
    allow_replan: true
    visualize: true

    safety_zone:
      manual: true
      unit_type: second
      collision_checking_deadline: 0.05
      slow_down_time: 0.2
      replan_deadline: 1.2
      look_ahead_time: 1.65

    collision_checker:
      distance: false
      continuous: false
      step: 0.1
      thread_count: 8
      realtime: false

    next_point_publisher:
      command_out_type: "trajectory_msgs/JointTrajectory"
      publish_joint_position: true
      publish_joint_velocity: false
      publish_joint_effort: false

    replanner:
      planner_name: ompl

    visualizer:
      publish_frequency: 10
      steo: 0.1
      topic: "/dynamic_safety/displayed_state"
